import { apiGet, BASE, openUser } from "./session.ts";
const dir = process.argv[2] as string;
const W = await openUser("B", dir, { profile: "wrong-otp-2" });
const { page } = W;
await page.goto(`${BASE}/onboarding`);
await page.getByRole("button", { name: "Get started" }).click();
await page.getByRole("button", { name: /Sign in or create a wallet/ }).click({ timeout: 30_000 });
await page.getByPlaceholder("Enter your email").fill(`venue0+wrongotp${Date.now() % 10000}+dynamic_test@example.com`);
await page.getByRole("button", { name: "Continue" }).click();
const code = page.locator("input[inputmode='numeric'], input[autocomplete='one-time-code']");
await code.first().waitFor({ timeout: 30_000 });
await code.first().click();
await page.keyboard.type("000000", { delay: 60 });
await page.waitForTimeout(6_000);
const text = (await page.locator("body").innerText()).replace(/\s+/g, " ");
const msg = text.match(/(invalid|incorrect|wrong)[^.]*\./i)?.[0] ?? "no error text";
const s = await apiGet<{ user: unknown }>(page, "/api/session");
await page.screenshot({ path: `${dir}/wrong-otp.png` });
console.log(`${s.user === null ? "PASS" : "FAIL"} wrong verification code: Dynamic says "${msg}"; server session=${JSON.stringify(s.user)}`);
await W.context.close();
