packages:
  - "packages/*"
  - "apps/*"
  - "campaign"
  - "scripts"
allowBuilds:
  '@reown/appkit': false
  bigint-buffer: false
  bufferutil: false
  esbuild: true
  protobufjs: true
  utf-8-validate: false
minimumReleaseAgeExclude:
  - ox@0.14.45
  - viem@2.56.7
  - '@dynamic-labs-wallet/core@1.1.12'
  - '@dynamic-labs-wallet/node-evm@1.1.12'
  - '@dynamic-labs-wallet/node@1.1.12'
  - '@dynamic-labs-wallet/primitives@1.1.12'
