import { readFile, writeFile } from "node:fs/promises";

const ARTIFACT = "contracts/out/Venue0Settlement.sol/Venue0Settlement.json";
const OUT = "packages/settlement/src/generated/venue0-settlement.ts";

const artifact = JSON.parse(await readFile(ARTIFACT, "utf8")) as { abi: unknown; bytecode: { object: string } };
const source = `// Generated by scripts/export-abi.ts from ${ARTIFACT}. Do not edit.
export const venue0SettlementAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;

export const venue0SettlementBytecode = "${artifact.bytecode.object}" as const;
`;
await writeFile(OUT, source);
console.log(`wrote ${OUT}`);
